#!/usr/bin/env python3
"""
Orca/PrusaSlicer post-processing script for BIGTREETECH TFT screens.

Combines several jobs into one pass over the sliced .gcode:

1) Converts the slicer's PNG thumbnail into the BIGTREETECH TFT's
   RGB565-hex format (multiple sizes), prepending it to the gcode file.
   Equivalent in behavior to BIQU's biqu_convert_p24.py but uses Pillow
   instead of PyQt5 so the resulting frozen .exe is much smaller.

2) After every M73 line emitted by the slicer (P=percent, R=minutes left),
   injects two M118 action:notification lines so a BTT TFT shows live
   Time Left and a 0-100% progress bar.

3) Strips M115 firmware-info queries from the file. They have no effect on
   a print but their multi-line response can race with M105 temperature
   polls on the serial line and overflow the RX buffer on hosts that proxy
   serial (Mintion Beagle camera, some ESP3D variants).
   See https://forum.prusa3d.com/forum/.../beagle-camera-v2-and-mk4/paged/4/

4) Upgrades the final pre-print M104 (set hotend temp, no wait) to M109
   (wait) when the slicer's auto-generated header forgot to wait. Works
   around OrcaSlicer issues #2334 and #4337 where the print starts moving
   before the nozzle has reached temperature.

5) Injects `M155 S<interval>` before the first executable command to
   throttle Marlin's automatic temperature auto-reports. Marlin's default
   is every 5 seconds; raising it to 30s cuts serial traffic ~6x and is
   the other half of keeping a Mintion Beagle from buffer-overflowing.

6) Moves the final "100% / 00:00:00" M118 notification pair to
   immediately before `action:print_end`, and drops any stray
   notifications that come after. Otherwise the TFT sees `print_end` and
   dismisses the print screen before it can show the completion state.

7) Strips the slicer's base64 PNG thumbnail block(s). We've already
   extracted the PNG and converted it to the BTT TFT format, so the
   payload (~50-200 KB per file) is dead weight on disk.

8) Strips Orca's full `; CONFIG_BLOCK_START ... ; CONFIG_BLOCK_END` slicer
   settings dump from the end of the file. ~30-60 KB on a typical print.
   Breaks Orca's "reload with config" feature -- enabled here because we
   target a print-and-throw-away gcode workflow.

9) Strips slicer "feature" comments and file-metadata comments that no
   firmware consumer reads (TYPE/WIDTH/HEIGHT/Z, WIPE_*, OBJECT_ID,
   HEADER/THUMBNAIL/EXECUTABLE block markers, `; generated by ...`,
   `; total layer number:`, `; filament_*:`, `; * extrusion width = *`).
   Preserves LAYER_CHANGE / LAYER_COUNT which BTT TFT firmware does read.

10) Strips the trailing `; comment` portion of lines that start with a G
    or M command (e.g. `G1 X10 ; whatever` -> `G1 X10`). Standalone
    comment lines and M117/M118 message commands are left alone.

11) Minifies float parameters on G/M lines: `X100.000` -> `X100`,
    `Z0.20` -> `Z0.2`, `F1500.0` -> `F1500`. Marlin parses these as
    floats so trailing-zero stripping is a behavioral no-op.

12) Trims trailing whitespace on every line.

13) Collapses blank lines.

Jobs 1-6 are content rewrites. Jobs 7-13 are size reductions: typical
savings on a fresh Orca slice are ~30% of file bytes.

Usage in Orca:
    Print Settings -> Others -> Post-processing scripts
        "C:\\Path\\To\\python.exe" "C:\\Path\\To\\btt_postprocess.py";
    or with the frozen .exe:
        "C:\\Path\\To\\btt_postprocess.exe";

Behavior notes:
- If the gcode has no thumbnail block (slicer setting disabled), the script
  skips the thumbnail step gracefully and still does the M73 conversion.
- Honors the SLIC3R_PP_OUTPUT_NAME environment variable: writes a sidecar
  .output_name file so the final filename gets a "_btt" suffix, matching
  the original BIQU script's behavior.
"""

from __future__ import annotations

import base64
import io
import os
import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("!!! Pillow is required. Run: pip install Pillow", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Thumbnail conversion (PNG base64 -> RGB565 hex blocks for BTT TFT)
# ---------------------------------------------------------------------------

# Sizes the BTT TFT firmware looks for in the gcode header, in order.
THUMBNAIL_SIZES: list[tuple[int, int]] = [
    (70, 70),
    (95, 80),
    (95, 95),
    (160, 140),
]

# RGB565 values that are visually black-ish but not exactly zero. The original
# BIQU script clamps these to pure black to avoid a faint speckle pattern on
# the TFT background. We preserve the same noise filter for compatibility.
NEAR_BLACK_RGB565 = {"0020", "0841", "0861"}


def rgb_to_rgb565_hex(r: int, g: int, b: int) -> str:
    """Pack an RGB888 triple into a 4-char big-endian RGB565 hex string."""
    pixel = (r << 16) | (g << 8) | b
    val = (
        ((pixel & 0x00F80000) >> 8)   # R: top 5 bits -> bits 11-15
        | ((pixel & 0x0000FC00) >> 5) # G: top 6 bits -> bits 5-10
        | ((pixel & 0x000000F8) >> 3) # B: top 5 bits -> bits 0-4
    )
    hex_val = f"{val:04x}"
    # Stomp near-black noise to true black, like the original script.
    return "0000" if hex_val in NEAR_BLACK_RGB565 else hex_val


def render_thumbnail_block(img: Image.Image, width: int, height: int) -> str:
    """
    Resize the source image to (width, height) and emit one BTT thumbnail
    block: a header line with size + one line per row of RGB565 hex pixels.
    """
    resized = img.resize((width, height), Image.LANCZOS).convert("RGB")
    pixels = resized.load()

    lines: list[str] = []
    # Header: ";WWWWHHHH" where each value is 4-char zero-padded hex.
    lines.append(f";{width:04x}{height:04x}\r\n")

    for y in range(height):
        row_chars = [";"]
        for x in range(width):
            r, g, b = pixels[x, y]
            row_chars.append(rgb_to_rgb565_hex(r, g, b))
        row_chars.append("\r\n")
        lines.append("".join(row_chars))

    return "".join(lines)


def extract_png_from_gcode(gcode_text: str) -> bytes | None:
    """
    Pull out the base64-encoded PNG between '; thumbnail begin' and
    '; thumbnail end' markers in slicer-emitted gcode. Returns the raw PNG
    bytes, or None if no thumbnail is present.
    """
    inside = False
    b64_chunks: list[str] = []

    for line in gcode_text.splitlines():
        if line.startswith("; thumbnail begin"):
            inside = True
            continue
        if line.startswith("; thumbnail end"):
            break
        if not inside:
            continue
        # Lines look like "; <base64 chars>"; strip the leading "; ".
        if line.startswith("; "):
            b64_chunks.append(line[2:].strip())
        else:
            b64_chunks.append(line.strip())

    if not b64_chunks:
        return None

    try:
        return base64.b64decode("".join(b64_chunks))
    except (ValueError, base64.binascii.Error) as exc:
        print(f"[btt_postprocess] thumbnail base64 decode failed: {exc}",
              file=sys.stderr)
        return None


def build_thumbnail_header(gcode_text: str) -> str:
    """
    Build the multi-size BTT thumbnail block to prepend to the gcode.
    Returns "" if there's no source thumbnail to work from.
    """
    png_bytes = extract_png_from_gcode(gcode_text)
    if png_bytes is None:
        print("[btt_postprocess] no thumbnail found in gcode; "
              "skipping thumbnail conversion.")
        return ""

    try:
        img = Image.open(io.BytesIO(png_bytes))
        img.load()  # force decode now so we surface errors here
    except Exception as exc:
        print(f"[btt_postprocess] failed to open thumbnail PNG: {exc}",
              file=sys.stderr)
        return ""

    parts: list[str] = []
    for w, h in THUMBNAIL_SIZES:
        parts.append(render_thumbnail_block(img, w, h))
    parts.append("; bigtree thumbnail end\r\n")
    return "".join(parts)


# ---------------------------------------------------------------------------
# M73 -> M118 action:notification injection
# ---------------------------------------------------------------------------

# Match an M73 line that has at least a P=percent token, optionally R=minutes.
M73_RE = re.compile(
    r"^\s*M73\b"
    r".*?P\s*(?P<p>\d+)"
    r"(?:.*?R\s*(?P<r>\d+))?",
    re.IGNORECASE,
)


def format_time_left(minutes: int) -> str:
    """Format remaining minutes as XXhYYmZZs (TFT firmware expected format)."""
    hours, mins = divmod(minutes, 60)
    return f"{hours:02d}h{mins:02d}m00s"


def build_m73_notifications(percent: int, minutes: int | None) -> list[str]:
    """Build the M118 lines to inject after an M73."""
    out = []
    if minutes is not None:
        out.append(
            f"M118 P0 A1 action:notification Time Left "
            f"{format_time_left(minutes)}\r\n"
        )
    out.append(
        f"M118 P0 A1 action:notification Data Left {percent}/100\r\n"
    )
    return out


def inject_m73_notifications(gcode_text: str) -> tuple[str, int]:
    """
    Walk the gcode line by line; after each real M73 line, append M118
    notifications. If the next line is already an M118 action:notification
    (file was post-processed before), skip the injection so re-runs stay
    idempotent. Returns (new_text, count_of_m73_lines_processed).
    """
    output: list[str] = []
    m73_count = 0

    # splitlines(keepends=True) preserves \r\n endings as-is.
    lines = gcode_text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        output.append(line)

        stripped = line.lstrip()
        if not stripped or stripped.startswith(";"):
            continue

        match = M73_RE.match(line)
        if not match:
            continue

        # Skip if a notification line already follows -- avoids stacking
        # duplicates when the script is run twice on the same file.
        next_line = lines[i + 1] if i + 1 < len(lines) else ""
        if "action:notification" in next_line:
            continue

        percent = int(match.group("p"))
        minutes = int(match.group("r")) if match.group("r") is not None else None
        output.extend(build_m73_notifications(percent, minutes))
        m73_count += 1

    return "".join(output), m73_count


# ---------------------------------------------------------------------------
# Serial-friendliness fixes for hosts that proxy the print line
# ---------------------------------------------------------------------------

_M115_RE = re.compile(r"^\s*M115\b", re.IGNORECASE)

# Match an extrusion move: G0/G1/G2/G3 with an E parameter. Once we hit one of
# these we're past the warmup region and into the actual print.
_EXTRUSION_RE = re.compile(r"^\s*G[0-3]\b(?=.*\bE-?\d)", re.IGNORECASE)

# M104/M109 with an S<temp> argument. The (?!\.\d) guard skips M104.1 etc.,
# which are filament-change variants with different semantics.
_M104_TEMP_RE = re.compile(
    r"^\s*M104(?!\.\d)\b.*?\bS\s*(?P<s>-?\d+)", re.IGNORECASE
)
# M109 accepts either S (wait while heating) or R (wait either direction);
# both count as "the printer will wait here", so we treat them equivalently.
_M109_WAIT_RE = re.compile(
    r"^\s*M109(?!\.\d)\b.*?\b[SR]\s*(?P<s>-?\d+)", re.IGNORECASE
)


def strip_m115_queries(text: str) -> tuple[str, int]:
    """Remove M115 firmware-info queries. Returns (new_text, removed_count)."""
    out: list[str] = []
    removed = 0
    for line in text.splitlines(keepends=True):
        if _M115_RE.match(line):
            removed += 1
            continue
        out.append(line)
    return "".join(out), removed


# Default interval (seconds) for M155 auto-temperature reports. Marlin's
# built-in default is 5s; raising this cuts serial traffic ~6x and helps
# serial-proxy hosts (Mintion Beagle) keep up. Adjust here if you want a
# different rate -- 60 is also reasonable.
M155_INTERVAL_SECONDS = 30

_M155_RE = re.compile(r"^\s*M155\b", re.IGNORECASE)


def inject_m155_throttle(
    text: str, interval_seconds: int = M155_INTERVAL_SECONDS,
) -> tuple[str, int]:
    """
    Insert an `M155 S<interval_seconds>` line just before the first
    executable command. If the file already has an M155 anywhere in the
    warmup region (user is managing this themselves), do nothing.

    Returns (new_text, 1) if a line was inserted, otherwise (text, 0).
    """
    lines = text.splitlines(keepends=True)
    first_exec_idx: int | None = None

    for i, line in enumerate(lines):
        stripped = line.lstrip()
        if not stripped or stripped.startswith(";"):
            continue
        if _EXTRUSION_RE.match(line):
            break
        if _M155_RE.match(line):
            return text, 0
        if first_exec_idx is None:
            first_exec_idx = i

    if first_exec_idx is None:
        return text, 0

    eol = "\r\n" if lines[first_exec_idx].endswith("\r\n") else "\n"
    lines.insert(first_exec_idx, f"M155 S{interval_seconds}{eol}")
    return "".join(lines), 1


def upgrade_final_warmup_m104_to_m109(text: str) -> tuple[str, int]:
    """
    Walk the file until the first extrusion move. Within that warmup window,
    track the most recent M104 S>0 that isn't followed by an M109 wait. If
    one remains at the end of the window, rewrite it to M109 so the printer
    waits for the nozzle before motion begins.

    Returns (new_text, 1) if a line was upgraded, otherwise (text, 0).
    """
    lines = text.splitlines(keepends=True)
    pending_m104: int | None = None

    for i, line in enumerate(lines):
        stripped = line.lstrip()
        if not stripped or stripped.startswith(";"):
            continue
        if _EXTRUSION_RE.match(line):
            break

        m109 = _M109_WAIT_RE.match(line)
        if m109 and int(m109.group("s")) > 0:
            # Printer will already wait here -- nothing earlier needs fixing.
            pending_m104 = None
            continue

        m104 = _M104_TEMP_RE.match(line)
        if m104 and int(m104.group("s")) > 0:
            pending_m104 = i

    if pending_m104 is None:
        return text, 0

    lines[pending_m104] = re.sub(
        r"\bM104\b", "M109", lines[pending_m104], count=1, flags=re.IGNORECASE,
    )
    return "".join(lines), 1


# ---------------------------------------------------------------------------
# End-of-print notification ordering
# ---------------------------------------------------------------------------

_PRINT_END_RE = re.compile(r"action:print_end\b", re.IGNORECASE)
_NOTIFICATION_RE = re.compile(r"action:notification\b", re.IGNORECASE)


def move_final_notifications_before_print_end(text: str) -> tuple[str, int]:
    """
    Slicer end-gcode usually fires `M118 P0 A1 action:print_end` BEFORE the
    final `M73 P100 R0`, which means the TFT sees `print_end` (and
    dismisses the print screen) before it ever sees the 100% / 00:00:00
    completion notification. Fix:

      1) Insert a fresh "100/100, 00h00m00s" notification pair immediately
         before the first `action:print_end` line.
      2) Drop any other `action:notification` lines that come AFTER
         `print_end`, so the TFT's state isn't bounced by stale updates
         after it's already shown "complete".

    Returns (new_text, 1) if reordering happened, else (text, 0).
    """
    lines = text.splitlines(keepends=True)
    print_end_idx: int | None = None
    for i, line in enumerate(lines):
        if _PRINT_END_RE.search(line):
            print_end_idx = i
            break

    if print_end_idx is None:
        return text, 0

    eol = "\r\n" if lines[print_end_idx].endswith("\r\n") else "\n"
    final_notifs = [
        f"M118 P0 A1 action:notification Time Left 00h00m00s{eol}",
        f"M118 P0 A1 action:notification Data Left 100/100{eol}",
    ]

    # Keep everything before print_end as-is; drop any post-print_end
    # notification lines so the TFT doesn't get re-triggered.
    before = lines[:print_end_idx]
    after = [
        line for line in lines[print_end_idx + 1:]
        if not _NOTIFICATION_RE.search(line)
    ]
    print_end_line = lines[print_end_idx]

    return "".join(before + final_notifs + [print_end_line] + after), 1


# ---------------------------------------------------------------------------
# Size-reduction passes
# ---------------------------------------------------------------------------

# Orca/Prusa emit thumbnails as `; thumbnail begin <w>x<h> <bytes>` /
# `; thumbnail end`, sometimes in multiple variants (thumbnail_QOI,
# thumbnail_JPG, etc.). We match all of them.
_THUMBNAIL_BEGIN_RE = re.compile(
    r"^;\s*thumbnail(?:_\w+)?\s+begin\b", re.IGNORECASE,
)
_THUMBNAIL_END_RE = re.compile(
    r"^;\s*thumbnail(?:_\w+)?\s+end\b", re.IGNORECASE,
)


def strip_png_thumbnail_blocks(text: str) -> tuple[str, int]:
    """
    Drop all `; thumbnail begin ... ; thumbnail end` blocks. We've already
    extracted the PNG and converted it to BTT format, so the base64
    payload is dead weight (50-200 KB per file, multiple blocks possible
    when the slicer emits QOI/JPG variants too).

    Returns (new_text, blocks_dropped).
    """
    output: list[str] = []
    inside = False
    blocks = 0
    for line in text.splitlines(keepends=True):
        if not inside and _THUMBNAIL_BEGIN_RE.match(line):
            inside = True
            blocks += 1
            continue
        if inside:
            if _THUMBNAIL_END_RE.match(line):
                inside = False
            continue
        output.append(line)
    return "".join(output), blocks


# Slicer-emitted comment lines that no Marlin / BTT TFT firmware consumer
# reads. Each pattern is anchored to a SPECIFIC well-known marker so we
# don't accidentally remove anything firmware-relevant (LAYER_CHANGE,
# LAYER_COUNT, AFTER_LAYER_CHANGE, etc. are intentionally NOT in the list).
_FEATURE_COMMENT_RE = re.compile(
    r"^;\s*("
    # Per-segment / per-layer slicer annotations
    r"TYPE:"                  # ;TYPE:Outer wall  (per-segment feature label)
    r"|WIDTH:"                # ;WIDTH:0.42       (per-segment line width)
    r"|HEIGHT:"               # ;HEIGHT:0.2       (already encoded in G1 Z)
    r"|Z:\d"                  # ;Z:0.2            (ditto)
    r"|CHANGE_LAYER\b"        # ;CHANGE_LAYER     (note: distinct from LAYER_CHANGE)
    r"|FEATURE:"              # Cura / older Prusa flavor
    r"|LINE_WIDTH:"
    # Wipe / flush / object markers
    r"|WIPE_START\b|WIPE_END\b"
    r"|FLUSH_START\b|FLUSH_END\b"
    r"|WIPE_TOWER_START\b|WIPE_TOWER_END\b"
    r"|OBJECT_ID:"
    r"|printing object\b"     # "; printing object Foo id:0 copy 0"
    # Orca structural block delimiters
    r"|HEADER_BLOCK_(?:START|END)\b"
    r"|THUMBNAIL_BLOCK_(?:START|END)\b"
    r"|EXECUTABLE_BLOCK_(?:START|END)\b"
    # Slicer-emitted file metadata (informational; not read by firmware)
    r"|generated by\b"
    r"|total layer number:"
    r"|filament(?:_\w+)?:"
    r"|max_z_height:"
    r"|.+ extrusion width\s*="
    # Klipper-flavor markers some Orca profiles emit
    r"|_SET_FAN_SPEED"
    r")",
    re.IGNORECASE,
)


def strip_slicer_feature_comments(text: str) -> tuple[str, int]:
    """
    Remove slicer-emitted comments that no downstream consumer reads.
    Preserves layer markers that BTT TFT firmware uses for the layer count
    display (LAYER_CHANGE, LAYER_NUM, LAYER_COUNT, BEFORE/AFTER_LAYER_CHANGE).

    Returns (new_text, dropped_count).
    """
    output: list[str] = []
    dropped = 0
    for line in text.splitlines(keepends=True):
        if _FEATURE_COMMENT_RE.match(line):
            dropped += 1
            continue
        output.append(line)
    return "".join(output), dropped


# Strip `; trailing comment` from lines that start with G or M. The
# negative lookahead for M117/M118 protects display/notification messages
# whose body could legitimately contain ';'.
_INLINE_COMMENT_RE = re.compile(
    r"^(\s*(?!M11[78]\b)[GM]\d+(?:\.\d+)?(?:[^;]*))\s*;.*$",
    re.IGNORECASE,
)


def strip_inline_command_comments(text: str) -> tuple[str, int]:
    """
    Convert `G1 X10 ; some note` -> `G1 X10`. Standalone comment lines
    (starting with `;`) are untouched here -- they're handled separately
    by strip_slicer_feature_comments / strip_png_thumbnail_blocks or kept.

    Returns (new_text, lines_modified).
    """
    output: list[str] = []
    modified = 0
    for line in text.splitlines(keepends=True):
        match = _INLINE_COMMENT_RE.match(line)
        if not match:
            output.append(line)
            continue
        if line.endswith("\r\n"):
            eol = "\r\n"
        elif line.endswith("\n"):
            eol = "\n"
        else:
            eol = ""
        new_line = match.group(1).rstrip() + eol
        if new_line != line:
            modified += 1
        output.append(new_line)
    return "".join(output), modified


# BTT thumbnail block markers. The header line is ";WWWWHHHH" (semicolon
# followed by exactly 8 hex chars and nothing else). The block terminates
# with our own "; bigtree thumbnail end" sentinel.
_BTT_HEADER_RE = re.compile(r"^;[0-9a-fA-F]{8}\s*$")
_BTT_END_RE = re.compile(r"^;\s*bigtree\s+thumbnail\s+end\b", re.IGNORECASE)


def strip_existing_btt_thumbnail(text: str) -> tuple[str, int]:
    """
    Remove any prior `;WWWWHHHH ... ; bigtree thumbnail end` block at the
    start of the file. Prevents doubling up the BTT thumbnail when this
    script is run a second time on its own output.

    Returns (new_text, blocks_dropped).
    """
    lines = text.splitlines(keepends=True)
    if not lines or not _BTT_HEADER_RE.match(lines[0]):
        return text, 0

    end_idx: int | None = None
    for i, line in enumerate(lines):
        if _BTT_END_RE.match(line):
            end_idx = i
            break

    if end_idx is None:
        # Looks like a BTT block start but no terminator found -- bail rather
        # than risk deleting unrelated content.
        return text, 0

    # Drop [0, end_idx] plus a single trailing blank line if present, since
    # render_thumbnail_block adds a "\r\n" gap after the sentinel.
    drop_through = end_idx + 1
    if drop_through < len(lines) and not lines[drop_through].strip():
        drop_through += 1
    return "".join(lines[drop_through:]), 1


# Orca's full slicer-config dump lives between these markers at the end
# of the file. ~30-60 KB of `;key = value` lines that no firmware reads
# and no host needs unless you "reload with config" in Orca.
_CONFIG_BLOCK_START_RE = re.compile(r"^;\s*CONFIG_BLOCK_START\b", re.IGNORECASE)
_CONFIG_BLOCK_END_RE = re.compile(r"^;\s*CONFIG_BLOCK_END\b", re.IGNORECASE)


def strip_slicer_config_block(text: str) -> tuple[str, int]:
    """
    Drop everything between `; CONFIG_BLOCK_START` and `; CONFIG_BLOCK_END`
    (inclusive). Breaks Orca's "reload with config" feature -- only enable
    if you don't rely on that.

    Returns (new_text, lines_dropped). Zero if either marker is missing.
    """
    lines = text.splitlines(keepends=True)
    start_idx: int | None = None
    end_idx: int | None = None
    for i, line in enumerate(lines):
        if start_idx is None and _CONFIG_BLOCK_START_RE.match(line):
            start_idx = i
        elif start_idx is not None and _CONFIG_BLOCK_END_RE.match(line):
            end_idx = i
            break

    if start_idx is None or end_idx is None:
        return text, 0

    dropped = end_idx - start_idx + 1
    del lines[start_idx:end_idx + 1]
    return "".join(lines), dropped


# Strip trailing zeros from float values on G/M command lines. Matches
# parameter letters Marlin actually treats as numeric. M117/M118 messages
# are excluded because the text body could contain digits we mustn't touch.
_FLOAT_PARAM_RE = re.compile(
    r"([XYZEFIJKAPSRQ])(-?\d+)\.(\d+)",
    re.IGNORECASE,
)


def _trim_trailing_zero(match: re.Match[str]) -> str:
    prefix, integer, decimals = match.group(1), match.group(2), match.group(3)
    decimals = decimals.rstrip("0")
    return f"{prefix}{integer}.{decimals}" if decimals else f"{prefix}{integer}"


def minify_float_coordinates(text: str) -> tuple[str, int]:
    """
    Strip trailing zeros and dangling decimal points from float parameters
    on G/M command lines: `X100.000` -> `X100`, `Z0.20` -> `Z0.2`,
    `F1500.0` -> `F1500`. Behavioral no-op since Marlin parses floats.

    Returns (new_text, lines_modified).
    """
    output: list[str] = []
    modified = 0
    for line in text.splitlines(keepends=True):
        stripped = line.lstrip()
        if not stripped or stripped.startswith(";"):
            output.append(line)
            continue
        # M117/M118 text bodies may contain digit-dot-zero sequences that
        # are part of the message, not gcode parameters.
        if re.match(r"\s*M11[78]\b", line, re.IGNORECASE):
            output.append(line)
            continue
        new_line = _FLOAT_PARAM_RE.sub(_trim_trailing_zero, line)
        if new_line != line:
            modified += 1
        output.append(new_line)
    return "".join(output), modified


def strip_trailing_whitespace(text: str) -> tuple[str, int]:
    """
    Trim trailing whitespace (spaces/tabs) from every line, preserving
    the line ending. Saves a byte here and there and prevents the
    collapse_blank_lines pass from treating "  \\r\\n" as content.

    Returns (new_text, lines_modified).
    """
    output: list[str] = []
    modified = 0
    for line in text.splitlines(keepends=True):
        if line.endswith("\r\n"):
            eol, content = "\r\n", line[:-2]
        elif line.endswith("\n"):
            eol, content = "\n", line[:-1]
        else:
            eol, content = "", line
        new_content = content.rstrip()
        if new_content != content:
            modified += 1
        output.append(new_content + eol)
    return "".join(output), modified


def collapse_blank_lines(text: str) -> tuple[str, int]:
    """Drop blank/whitespace-only lines. Returns (new_text, dropped_count)."""
    output: list[str] = []
    dropped = 0
    for line in text.splitlines(keepends=True):
        if not line.strip():
            dropped += 1
            continue
        output.append(line)
    return "".join(output), dropped


# ---------------------------------------------------------------------------
# Output filename hint (matches BIQU script behavior)
# ---------------------------------------------------------------------------

def write_output_name_hint(gcode_path: Path) -> None:
    """
    Some slicers (PrusaSlicer/Orca) honor a "<gcode>.output_name" sidecar
    file to rename the post-processed file. We use it to add a "_btt"
    suffix, matching the original BIQU script.
    """
    env_name = os.getenv("SLIC3R_PP_OUTPUT_NAME")
    if not env_name:
        return  # not running under a slicer that sets this; that's fine

    base, ext = os.path.splitext(env_name)
    final_name = f"{base}_btt{ext}"
    sidecar = gcode_path.with_name(gcode_path.name + ".output_name")
    try:
        sidecar.write_text(final_name, encoding="utf-8")
    except OSError as exc:
        print(f"[btt_postprocess] could not write output_name sidecar: {exc}",
              file=sys.stderr)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def process_gcode(path: Path) -> None:
    """Run all transformations on the file, in place."""
    # Read raw to preserve line endings as much as possible. The slicer
    # writes UTF-8; replacement on errors keeps us robust to odd bytes.
    text = path.read_text(encoding="utf-8", errors="replace")
    original_size = len(text)

    # If this file was already post-processed, drop the existing BTT
    # thumbnail block so we don't stack a second one on top.
    text, prior_btt_dropped = strip_existing_btt_thumbnail(text)

    # Build the BTT thumbnail header first -- it reads the original PNG
    # block, which subsequent passes are about to strip.
    thumbnail_header = build_thumbnail_header(text)

    new_text = text
    # Content rewrites first.
    new_text, m73_count = inject_m73_notifications(new_text)
    new_text, m115_stripped = strip_m115_queries(new_text)
    new_text, m104_upgraded = upgrade_final_warmup_m104_to_m109(new_text)
    new_text, m155_injected = inject_m155_throttle(new_text)
    new_text, end_notif_moved = move_final_notifications_before_print_end(new_text)
    # Size reductions last -- they only remove bytes, never change semantics.
    new_text, png_blocks_stripped = strip_png_thumbnail_blocks(new_text)
    new_text, config_block_dropped = strip_slicer_config_block(new_text)
    new_text, feature_cmts_stripped = strip_slicer_feature_comments(new_text)
    new_text, inline_cmts_stripped = strip_inline_command_comments(new_text)
    new_text, minified_lines = minify_float_coordinates(new_text)
    new_text, ws_trimmed = strip_trailing_whitespace(new_text)
    new_text, blanks_collapsed = collapse_blank_lines(new_text)

    final_text = thumbnail_header + new_text
    path.write_text(final_text, encoding="utf-8")
    write_output_name_hint(path)

    final_size = len(final_text)
    delta_pct = (
        (final_size - original_size) / original_size * 100
        if original_size else 0.0
    )
    has_thumb = "yes" if thumbnail_header else "no"
    print(f"[btt_postprocess] {path.name}: "
          f"thumb={has_thumb} m73={m73_count} m115={m115_stripped} "
          f"m104_fix={m104_upgraded} m155={m155_injected} "
          f"end_notif={end_notif_moved} "
          f"png={png_blocks_stripped} cfg={config_block_dropped} "
          f"feat={feature_cmts_stripped} inline={inline_cmts_stripped} "
          f"minify={minified_lines} ws={ws_trimmed} "
          f"blanks={blanks_collapsed} prior_btt={prior_btt_dropped} "
          f"size={original_size}->{final_size} ({delta_pct:+.1f}%)")


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("Usage: btt_postprocess <gcode_file>", file=sys.stderr)
        return 1

    target = Path(argv[1])
    if not target.is_file():
        print(f"File not found: {target}", file=sys.stderr)
        return 1

    try:
        process_gcode(target)
    except Exception as exc:
        # Never crash the slicer's pipeline silently -- log and exit nonzero.
        print(f"[btt_postprocess] ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


def cli() -> None:
    """Console script entry point for pip-installed use."""
    sys.exit(main(sys.argv))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
